# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 90527b0ddfe4a8b024e3f576f02edf57fd0835656eba5648c1a12c5ad62bf9b090763a1c9411ca8141325059ebccbc4eb50637ddd7fda75f59eb963dc958e137

test:
  secret_key_base: 188c02678cb1bf87d46db0597e372cfecb8063adb5f7984f09511c4b9a21625664aab5972079f049682c6f62aca0b5d66429f1df353f1a9c95c3f42db9cee98a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
